// Mocks generated by Mockito 5.4.2 from annotations
// in getx_testing/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:dartz/dartz.dart' as _i3;
import 'package:get/get.dart' as _i2;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i7;
import 'package:getx_testing/abstract_repos/get_riddle.dart' as _i9;
import 'package:getx_testing/error/failure.dart' as _i10;
import 'package:getx_testing/RANDOM/riddle/controller/riddle_controller.dart'
    as _i4;
import 'package:getx_testing/RANDOM/riddle/model/riddle_model.dart' as _i5;
import 'package:getx_testing/repo_impl/get_riddle.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRxBool_0 extends _i1.SmartFake implements _i2.RxBool {
  _FakeRxBool_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRx_1<T> extends _i1.SmartFake implements _i2.Rx<T> {
  _FakeRx_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_2<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RiddleController].
///
/// See the documentation for Mockito's code generation for more information.
class MockRiddleController extends _i1.Mock implements _i4.RiddleController {
  MockRiddleController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RxBool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: _FakeRxBool_0(
          this,
          Invocation.getter(#isLoading),
        ),
      ) as _i2.RxBool);
  @override
  _i2.RxBool get isShowed => (super.noSuchMethod(
        Invocation.getter(#isShowed),
        returnValue: _FakeRxBool_0(
          this,
          Invocation.getter(#isShowed),
        ),
      ) as _i2.RxBool);
  @override
  _i2.Rx<_i5.RiddleModel?> get riddle => (super.noSuchMethod(
        Invocation.getter(#riddle),
        returnValue: _FakeRx_1<_i5.RiddleModel?>(
          this,
          Invocation.getter(#riddle),
        ),
      ) as _i2.Rx<_i5.RiddleModel?>);
  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);
  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);
  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);
  @override
  _i6.Future<void> getRiddle() => (super.noSuchMethod(
        Invocation.method(
          #getRiddle,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  bool showOnTap() => (super.noSuchMethod(
        Invocation.method(
          #showOnTap,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i6.Future<void> onInit() => (super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Disposer addListener(_i7.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i7.Disposer);
  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListenerId(
    Object? id,
    _i8.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Disposer addListenerId(
    Object? key,
    _i7.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i7.Disposer);
  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GetRiddle].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRiddle extends _i1.Mock implements _i9.GetRiddle {
  MockGetRiddle() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<_i10.Failure, _i5.RiddleModel>> getDataFromApi() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDataFromApi,
          [],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i10.Failure, _i5.RiddleModel>>.value(
                _FakeEither_3<_i10.Failure, _i5.RiddleModel>(
          this,
          Invocation.method(
            #getDataFromApi,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i10.Failure, _i5.RiddleModel>>);
}

/// A class which mocks [GetRiddleImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRiddleImpl extends _i1.Mock implements _i11.GetRiddleImpl {
  MockGetRiddleImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<_i10.Failure, _i5.RiddleModel>> getDataFromApi() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDataFromApi,
          [],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i10.Failure, _i5.RiddleModel>>.value(
                _FakeEither_3<_i10.Failure, _i5.RiddleModel>(
          this,
          Invocation.method(
            #getDataFromApi,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i10.Failure, _i5.RiddleModel>>);
}
